#+title: Listy i ich metody
#+author: Dawid NPM8 Małysa
#+options: timestamp:nil

** Listy (Arrays)
   W JavaScript, listy, znane również jako tablice, służą do przechowywania wielu wartości w jednej zmiennej.
   Możemy do nich dodawać nowe elementy, a także usuwać, odczytywać i modyfikować już istniejące elementy.

   #+REVEAL: split

   #+begin_src javascript
    const cars = ["Saab", "Volvo", "BMW"];

    console.log(cars[0]); // Saab
    cars[0] = "Opel"
    console.log(cars); // Opel, Volvo, BMW
   #+end_src

   #+REVEAL: split

   #+begin_src javascript
    const cars = ["Saab", "Volvo", "BMW"];
    
    const lastElementIndex = cars.length - 1;
    console.log(lastElementIndex); // 2
    console.log(cars[lastElementIndex]); // BMW
   #+end_src

** Iterowanie po liście

   Iteracja to proces przejścia przez każdy element w danej kolekcji danych, takiej jak lista, i wykonanie określonej operacji na każdym z tych elementów.

   #+REVEAL: split

   #+begin_src javascript
    const cars = ["Saab", "Volvo", "BMW"];

    for (let i = 0; i < cars.length; i++) {
        console.log(cars[i]);
    }
   #+end_src

   #+REVEAL: split

   #+begin_src javascript
    const cars = ["Saab", "Volvo", "BMW"];

    for (const car of cars) {
        console.log(car);
    }
   #+end_src

*** Benchmark

   Która z pętli jest szybsza? Czy one w ogóle są szybkie? Dowiedzmy się!

   [[https://jsben.ch/IQxsr][Wyniki]]


** Wartości i ich referencje
   W JavaScript, kiedy przypisujemy jedną zmienną o wartości typu złożonego do drugiej, to przypisujemy referencję do tej zmiennej, a nie jej wartość.
   Oznacza to, że obie zmienne wskazują na ten sam obiekt w pamięci.

   #+REVEAL: split
   
   #+begin_src javascript
    const cars = ["Saab", "Volvo", "Ferrari"];
    const cars2 = cars;

    c = cars[0]

    cars2[0] = "Opel";

    cars.push("BMW");

    console.log(cars); // Opel, Volvo, Ferrari, BMW 

    console.log(c); // Saab

   #+end_src

** Metody list
   W JavaScript, listy mają wiele wbudowanych metod, które pozwalają na łatwe manipulowanie elementami listy.

   #+REVEAL: split

*** push() i pop()
    - =push()= - dodaje nowy element na końcu listy, 
    - =pop()= - usuwa ostatni element z listy.

   #+REVEAL: split

   #+begin_src javascript
    const cars = ["Saab", "Volvo", "BMW"];

    cars.push("Ferrari"); // Dodaje element na końcu listy
    console.log(cars); // Saab, Volvo, BMW, Ferrari

    const lastCar = cars.pop(); // Usuwa ostatni element z listy
    console.log(cars); // Saab, Volvo, BMW
    console.log(lastCar); // Ferrari
   #+end_src

*** shift() i unshift()
    - =shift()= - usuwa pierwszy element z listy,
    - =unshift()= - dodaje nowy element na początku listy.

   #+REVEAL: split

   #+begin_src javascript
    cars.shift(); // Usuwa pierwszy element z listy
    console.log(cars); // Volvo, BMW

    cars.unshift("Opel"); // Dodaje element na początku listy
    console.log(cars); // Opel, Volvo, BMW
   #+end_src

*** indexOf() i includes()
    - =indexOf()= - zwraca indeks pierwszego wystąpienia elementu w liście, 
    - =includes()= - zwraca true jeśli element występuje w liście, w przeciwnym wypadku zwraca false.

   #+REVEAL: split

   #+begin_src javascript
    const doIHaveVolvo = cars.includes("Volvo"); // Sprawdza czy element znajduje się na liście
    console.log(doIHaveVolvo); // true
   #+end_src

   #+REVEAL: split

   #+begin_src javascript
    const indexOfVolvo = cars.indexOf("Volvo"); // Zwraca indeks elementu na liście
    console.log(indexOfVolvo); // 1
   #+end_src

*** slice() i splice()
    - =slice()= - zwraca nową listę, która jest częścią starej listy, 
    - =splice()= - usuwa elementy z listy, lub je zamienia.

   #+REVEAL: split

   #+begin_src javascript
    cars.splice(1, 0, "Ferrari"); // Dodaje element na indeksie 1
    console.log(cars); // Opel, Ferrari, Volvo, BMW

    cars.splice(1, 1); // Usuwa element na indeksie 1
    console.log(cars); // Opel, Volvo, BMW
   #+end_src

*** sort() i reverse()
    - =sort()= - sortuje listę alfabetycznie, 
    - =reverse()= - odwraca kolejność elementów na liście.

   #+REVEAL: split

   #+begin_src javascript
    cars.reverse(); // Odwraca kolejność elementów w liście
    console.log(cars); // BMW, Volvo, Opel

    cars.sort(); // Sortuje elementy w liście
    console.log(cars); // BMW, Opel, Volvo
   #+end_src

   #+REVEAL: split

   #+begin_src javascript
    const newCars = cars.concat(["Ferrari", "Saab"]); // Łączy dwie listy
    console.log(newCars); // BMW, Opel, Volvo, Ferrari, Saab
   #+end_src

** Ciekawostki

   #+REVEAL: split

   #+begin_src javascript
    const cars = ["Saab", "Volvo", "BMW"];

    // Dodaje element na indeksie 3
    cars[3] = "Ferrari";
    console.log(cars);
    // Saab, Volvo, BMW, Ferrari

    // Dodaje element na indeksie 10
    cars[10] = "Ferrari"; 
    console.log(cars); 
    // Saab, Volvo, BMW, Ferrari, undefined, undefined, undefined, undefined, undefined, undefined, Ferrari

    // Dodaje element na indeksie 5
    cars[5] = "Ferrari"; 
    console.log(cars); 
    // Saab, Volvo, BMW, Ferrari, undefined, Ferrari, undefined, undefined, undefined, undefined, Ferrari

    // Usuwa element na indeksie 3
    cars[3] = undefined;
    console.log(cars); 
    // Saab, Volvo, BMW, undefined, undefined, Ferrari, undefined, undefined, undefined, undefined, Ferrari

    // Dodaje element na indeksie 3
    cars[3] = null; 
    console.log(cars); 
    // Saab, Volvo, BMW, null, undefined, Ferrari, undefined, undefined, undefined, undefined, Ferrari

    // Dodaje element na indeksie 3
    cars[3] = 0; 
    console.log(cars); 
    // Saab, Volvo, BMW, 0, undefined, Ferrari, undefined, undefined, undefined, undefined, Ferrari

    // Dodaje element na indeksie 3
    cars[3] = "";
    console.log(cars);
    // Saab, Volvo, BMW, "", undefined, Ferrari, undefined, undefined, undefined, undefined, Ferrari

    // Dodaje element na indeksie 3
    cars[3] = false; 
    console.log(cars); 
    // Saab, Volvo, BMW, false, undefined, Ferrari, undefined, undefined, undefined, undefined, Ferrari

   #+end_src

   #+REVEAL: split

   #+begin_src javascript
    const cars = ["Saab", "Volvo", "BMW"];
    cars.length = 0; // Usuwa wszystkie elementy z listy
    
    console.log(cars); // []
    
    cars.length = 5; // Dodaje 5 elementów o wartości undefined do listy
    
    console.log(cars); // [undefined, undefined, undefined, undefined, undefined]

   #+end_src
